/**
 * HTML Sanitization Utility
 * Prevents XSS attacks by cleaning user-generated and external HTML content
 * 
 * SECURITY: This is a CRITICAL security component. Do not modify without security review.
 * 
 * Used for:
 * - Email bodies from Gmail/Outlook (attacker-controlled)
 * - AI-generated HTML responses (prompt injection risk)
 * - User-provided HTML content
 * 
 * Compliant with: OWASP XSS Prevention Cheat Sheet
 */

import DOMPurify from 'isomorphic-dompurify';

/**
 * Sanitize HTML content to prevent XSS attacks
 * 
 * @param html - Raw HTML string (potentially malicious)
 * @param options - Custom sanitization options
 * @returns Safe HTML string with all dangerous elements/attributes removed
 * 
 * @example
 * const maliciousHTML = '<img src=x onerror=alert(1)><script>steal()</script>';
 * const safeHTML = sanitizeHTML(maliciousHTML);
 * // Result: '<img src=x>'
 */
export function sanitizeHTML(
  html: string,
  options?: {
    allowImages?: boolean;
    allowLinks?: boolean;
    allowStyles?: boolean;
  }
): string {
  if (!html) return '';

  const defaultOptions = {
    allowImages: true,
    allowLinks: true,
    allowStyles: false,
    ...options
  };

  // Define allowed HTML tags (whitelist approach)
  const ALLOWED_TAGS = [
    // Text formatting
    'b', 'i', 'u', 'strong', 'em', 'mark', 'small', 'del', 'ins', 'sub', 'sup',
    // Structure
    'p', 'br', 'span', 'div', 'hr',
    // Headings
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    // Lists
    'ul', 'ol', 'li',
    // Quotes and code
    'blockquote', 'code', 'pre',
    // Tables (for email signatures)
    'table', 'thead', 'tbody', 'tr', 'td', 'th',
  ];

  // Conditionally add images and links
  if (defaultOptions.allowImages) {
    ALLOWED_TAGS.push('img');
  }
  if (defaultOptions.allowLinks) {
    ALLOWED_TAGS.push('a');
  }

  // Allowed attributes (whitelist)
  const ALLOWED_ATTR = [
    'class', 'id', 'title',
    ...(defaultOptions.allowLinks ? ['href', 'target', 'rel'] : []),
    ...(defaultOptions.allowImages ? ['src', 'alt', 'width', 'height'] : []),
    ...(defaultOptions.allowStyles ? ['style'] : []),
  ];

  // Sanitize with DOMPurify
  const cleaned = DOMPurify.sanitize(html, {
    ALLOWED_TAGS,
    ALLOWED_ATTR,
    
    // Only allow safe URL protocols
    ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto):|[^a-z]|[a-z+.-]+(?:[^a-z+.\-:]|$))/i,
    
    // Explicitly forbid dangerous tags
    FORBID_TAGS: [
      'script', 'style', 'iframe', 'object', 'embed', 'applet',
      'base', 'form', 'input', 'button', 'select', 'textarea',
      'link', 'meta', 'svg', 'math'
    ],
    
    // Forbid event handlers and dangerous attributes
    FORBID_ATTR: [
      'onerror', 'onload', 'onclick', 'onmouseover', 'onmouseout',
      'onfocus', 'onblur', 'onchange', 'onsubmit', 'onreset',
      'action', 'formaction', 'srcdoc', 'sandbox'
    ],
    
    // Additional security options
    ALLOW_DATA_ATTR: false, // Block data-* attributes
    ALLOW_UNKNOWN_PROTOCOLS: false,
    SAFE_FOR_TEMPLATES: true,
    WHOLE_DOCUMENT: false,
    RETURN_DOM: false,
    RETURN_DOM_FRAGMENT: false,
    RETURN_TRUSTED_TYPE: false,
    FORCE_BODY: false,
    
    // Sanitize in place
    IN_PLACE: false,
    
    // Keep comments for debugging (but remove <script> content)
    KEEP_CONTENT: false,
  });

  return cleaned;
}

/**
 * Sanitize HTML specifically for email bodies
 * More permissive than default (allows tables, images, styles for signatures)
 * 
 * @param emailHTML - Email body HTML
 * @returns Sanitized email HTML
 */
export function sanitizeEmailHTML(emailHTML: string): string {
  return sanitizeHTML(emailHTML, {
    allowImages: true,
    allowLinks: true,
    allowStyles: true, // Email signatures often use inline styles
  });
}

/**
 * Sanitize AI-generated HTML responses
 * Strict sanitization (no images, no styles)
 * 
 * @param aiHTML - HTML generated by OpenAI
 * @returns Sanitized AI response
 */
export function sanitizeAIHTML(aiHTML: string): string {
  return sanitizeHTML(aiHTML, {
    allowImages: false,
    allowLinks: true,
    allowStyles: false,
  });
}

/**
 * Escape HTML entities for plain text rendering
 * Use this when you want to display HTML as text (not render it)
 * 
 * @param text - Text that may contain HTML
 * @returns HTML-escaped text
 * 
 * @example
 * escapeHTML('<script>alert(1)</script>')
 * // Returns: '&lt;script&gt;alert(1)&lt;/script&gt;'
 */
export function escapeHTML(text: string): string {
  if (!text) return '';

  const htmlEscapeMap: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#x27;',
    '/': '&#x2F;',
  };

  return text.replace(/[&<>"'/]/g, (char) => htmlEscapeMap[char] || char);
}

/**
 * Strip all HTML tags from content
 * Use for notification messages, SMS, or plain text display
 * 
 * @param html - HTML content
 * @returns Plain text without any HTML
 */
export function stripHTML(html: string): string {
  if (!html) return '';
  
  // First sanitize to remove dangerous content
  const sanitized = sanitizeHTML(html);
  
  // Then strip all HTML tags
  return sanitized.replace(/<[^>]*>/g, '').trim();
}

/**
 * Validate and sanitize URL
 * Prevents javascript:, data:, and other dangerous protocols
 * 
 * @param url - URL to validate
 * @returns Safe URL or '#' if invalid
 */
export function sanitizeURL(url: string): string {
  if (!url) return '#';

  const trimmed = url.trim().toLowerCase();

  // Block dangerous protocols
  const dangerousProtocols = [
    'javascript:',
    'data:',
    'vbscript:',
    'file:',
    'about:',
  ];

  if (dangerousProtocols.some((protocol) => trimmed.startsWith(protocol))) {
    console.warn(`[SECURITY] Blocked dangerous URL protocol: ${url}`);
    return '#';
  }

  // Allow only safe protocols
  if (!url.match(/^(https?:\/\/|mailto:|\/|#)/i)) {
    console.warn(`[SECURITY] Invalid URL protocol: ${url}`);
    return '#';
  }

  return url;
}

/**
 * Check if content contains potentially malicious code
 * Used for additional validation before processing
 * 
 * @param content - Content to check
 * @returns true if malicious patterns detected
 */
export function containsMaliciousCode(content: string): boolean {
  if (!content) return false;

  const maliciousPatterns = [
    /<script[\s>]/i,
    /javascript:/i,
    /on\w+\s*=/i, // onclick, onerror, etc.
    /<iframe/i,
    /eval\s*\(/i,
    /expression\s*\(/i,
    /-moz-binding/i,
    /data:text\/html/i,
    /<object/i,
    /<embed/i,
    /<applet/i,
  ];

  const detected = maliciousPatterns.some((pattern) => pattern.test(content));

  if (detected) {
    console.warn('[SECURITY] Malicious code pattern detected in content');
  }

  return detected;
}

/**
 * Test suite for sanitization (run in development)
 */
export function runSanitizationTests(): void {
  if (process.env.NODE_ENV !== 'development') {
    console.warn('Sanitization tests should only run in development');
    return;
  }

  const tests = [
    {
      name: 'XSS via onerror',
      input: '<img src=x onerror=alert(1)>',
      expected: (output: string) => !output.includes('onerror'),
    },
    {
      name: 'Script tag',
      input: '<script>alert(document.cookie)</script>',
      expected: (output: string) => !output.includes('<script>'),
    },
    {
      name: 'Iframe injection',
      input: '<iframe src="javascript:alert(1)"></iframe>',
      expected: (output: string) => !output.includes('<iframe'),
    },
    {
      name: 'Event handler attributes',
      input: '<div onclick="steal()">Click me</div>',
      expected: (output: string) => !output.includes('onclick'),
    },
    {
      name: 'Data URL in image',
      input: '<img src="data:text/html,<script>alert(1)</script>">',
      expected: (output: string) => !output.includes('data:'),
    },
    {
      name: 'Safe content preservation',
      input: '<p>Hello <strong>World</strong></p>',
      expected: (output: string) => output.includes('<p>') && output.includes('<strong>'),
    },
  ];

  console.log('🧪 Running HTML Sanitization Tests...\n');

  tests.forEach(({ name, input, expected }) => {
    const output = sanitizeHTML(input);
    const passed = expected(output);

    console.log(`${passed ? '✅' : '❌'} ${name}`);
    console.log(`   Input:  ${input}`);
    console.log(`   Output: ${output}\n`);
  });
}
